#!/usr/bin/env bash

# TODO: support windows builds/installs
#       copy dlls

# nsfu
cd "$(dirname "$0")"
if [ -f ".env" ]; then
  export $(grep -v '^#' .env | xargs -d '\n')
fi

HOST=$(go env | grep GOHOSTOS | cut -d'=' -f2)
ARCH=$(go env | grep GOARCH | cut -d'=' -f2)

INSTALL_DIR=`eval echo $INSTALL_DIR`

set -x

if [ "$1" = "run" ]; then
  go run cmd/yams/yams.go
elif [ "$1" = "dev" ]; then
  export DEV=1
  go run cmd/yams/yams.go
elif [ "$1" = "install" ]; then
  mkdir -p $INSTALL_DIR

  if [ "$HOST" = "windows" ]; then
    dllmod=$(echo "$(grep 'github.*tags' go.mod)" | sed -E 's/^[^a-zA-Z]*//; s/[[:space:]]+/@/')
    modcache=$(go env GOMODCACHE)
    cp "$(go env GOMODCACHE)/$dllmod/lib/$HOST/$ARCH/bin/"* $INSTALL_DIR/
  fi

  go build -o $INSTALL_DIR/ cmd/yams/yams.go
elif [ "$1" = "uninstall" ]; then
  rm $INSTALL_DIR/yams
elif [ "$1" = "build" ]; then
  mkdir -p build
  go build -o build/ cmd/yams/yams.go
elif [ "$1" = "clean" ]; then
  rm -rf build/
else
  set +x
  echo "Shiver me timbers!!.. Invalid arrghh - $1"
  exit 1
fi



