#!/bin/bash
# TODO: support windows builds/installs
#       copy dlls

# nsfu
cd "$(dirname "$0")"
if [ -f ".env" ]; then
  export $(grep -v '^#' .env | xargs -d '\n')
fi

set -x

if [ "$1" = "run" ]; then
  go run cmd/yams/yams.go
elif [ "$1" = "dev" ]; then
  export DEV=1
  go run cmd/yams/yams.go
elif [ "$1" = "install" ]; then
  mkdir -p $INSTALL_DIR
  go build -o $INSTALL_DIR/ cmd/yams/yams.go
elif [ "$1" = "uninstall" ]; then
  rm ~/Apps/bin/yams
elif [ "$1" = "build" ]; then
  mkdir -p build
  go build -o build/ cmd/yams/yams.go
elif [ "$1" = "clean" ]; then
  rm -rf build/
else
  set +x
  echo "Shiver me timbers!!.. Invalid arrghh - $1"
  exit 1
fi



